import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Slider from '../components/slider'

export default function Home() {
return (

<div className={styles.container}>

  {/* ------------------- Head ------------------- */}

  <Head>
    <title>Tsunami Clapham</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/vectors/favicon.svg" />
  </Head>

  {/* ------------------- Canvas ------------------- */}
  <Slider />

  {/* ------------------- Header ------------------- */}
  <header className={styles.header}>
    <Image src="/vectors/logo.svg" alt="Bespoke Programming Logo" width={100} height={24} />
  </header>

  {/* ------------------- Main ------------------- */}
  <main className={styles.main}>
    <h1 className={styles.title}>
      Welcome to Tsunami!
    </h1>
    <p className={styles.description}>
      Explore our menu.
    </p>
  </main>

  {/* ------------------- Footer ------------------- */}
  <footer className={styles.footer}>
    <p>© 2022</p>
    <span className={styles.logo}>
      <Image src="/vectors/BespokeProgrammingLogo.svg" alt="Bespoke Programming Logo" width={32} height={24} />
    </span>
    <p>Bespoke Programming</p>
  </footer>

</div>
)
}