import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
return (
<div className={styles.container}>

  <Head>
    <title>Tsunami Clapham</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.svg" />
  </Head>

  <header>
  <Image src="/logo.svg" alt="Bespoke Programming Logo" width={100} height={24} />
  </header>

  <main className={styles.main}>
    <h1 className={styles.title}>
      Welcome to Tsunami!
    </h1>

    <p className={styles.description}>
      Explore our menu.
    </p>
  </main>

  <footer className={styles.footer}>
      <p>© 2022</p>
      <span className={styles.logo}>
        <Image src="/BespokeProgrammingLogo.svg" alt="Bespoke Programming Logo" width={32} height={24} />
      </span>
      <p>Bespoke Programming</p>
  </footer>

</div>
)
}